### ISSUE TITLE
Sending Amounts with 7 Decimal or more Fails

### ISSUE THREAD

**Issue by daygle** [litecoincash-project/litecoincash#11]
I am finding that when attempting to send a transaction with 7 or more decimals the send fails.

Is anyone else experiencing this?

Is there anything I can do to allow decimals greater than 6?

**Comment by litecoincash-project** [comment]
7 decimal places should be fine (example: https://chainz.cryptoid.info/lcc/tx.dws?21854288.htm), though 8 is impossible due to our coin scaling. Can you show an example which fails with 7 dp?

**Comment by litecoincash-project** [comment]
Assuming you fixed your code :)
