### ISSUE TITLE
Error When Make - Debian 8

### ISSUE THREAD

**Issue by daygle** [litecoincash-project/litecoincash#12]
I am getting the below error when performing a make when using the latest git. Any ideas why?

./uint256.h:48:24: note:   no known conversion for argument 1 from ‘CTxDestination {aka boost::variant<CNoDestination, CKeyID, CScriptID, WitnessV0ScriptHash, WitnessV0KeyHash, WitnessUnknown>}’ to ‘const base_blob<160u>&’
./uint256.h:48:24: note: bool operator!=(const base_blob<256u>&, const base_blob<256u>&)
./uint256.h:48:24: note:   no known conversion for argument 1 from ‘CTxDestination {aka boost::variant<CNoDestination, CKeyID, CScriptID, WitnessV0ScriptHash, WitnessV0KeyHash, WitnessUnknown>}’ to ‘const base_blob<256u>&’
Makefile:5869: recipe for target 'libbitcoin_server_a-pow.o' failed
make[2]: *** [libbitcoin_server_a-pow.o] Error 1
make[2]: Leaving directory '/home/wallets/litecoincash/src'
Makefile:9690: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wallets/litecoincash/src'
Makefile:736: recipe for target 'all-recursive' failed

**Comment by red0bear** [comment]
Try make again  ..... or just re download the wallet please.

**Comment by daygle** [comment]
@red0bear Already tried that...

**Comment by red0bear** [comment]
@daygle hummm did you make a correct check dependecies ? OH is Debian .... you are so hardcore hehehehe

**Comment by daygle** [comment]
@red0bear Sure did, I had this wallet running before then performed a pull and now I receive this error.

**Comment by red0bear** [comment]
The problem may be debian ....... they always far behind and work files .... go different  .... in opensuse works well ...

**Comment by daygle** [comment]
I am still receiving this issue. Does anyone alse have a solution for Debian 8? I don't want to swap my operating system.

I would guess all Debian and Ubuntu users are unable to compile this wallet. The last commit I was able to compile was 3bcc790cacad47421848d821b9ba18d8c86a5f7b. After that I receive the above reported error.

@litecoincash-project Are you able to comment on this one?

**Comment by blockester** [comment]
What are your make configuration parameters?

**Comment by litecoincash-project** [comment]
Assuming stale and closing.
