### ISSUE TITLE
getinfo flag does nothing

### ISSUE THREAD

**Issue by crusher72** [litecoincash-project/litecoincash#13]
https://github.com/litecoincash-project/litecoincash/blob/adcfb6f9437a89f212fa9341d453ae1d4809ace7/src/rpc/misc.cpp#L634

-getinfo should format everything into the old format. It does nothing currently.

**Comment by blockester** [comment]
getinfo (deprecated)
        This call was removed in BTC version 0.16.0. Use the appropriate fields from:
        - getblockchaininfo: blocks, difficulty, chain
        - getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings
        - getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion
        litecoincash-cli has the option -getinfo to collect and format these in the old format.
