### ISSUE TITLE
When create bee with honey address return error

### ISSUE THREAD

**Issue by riotom** [litecoincash-project/litecoincash#15]
When i try 

    ./litecoincash-cli createbees 1 false MDwASjngYWi4XAххх

it return 

    {"result":null,"error":{"code":-64,"message":"Error: If specifying a honey address, it must be legacy format (TX_PUBKEYHASH)"},"id":"curltest"}

But when i try without honey address bee created success

**Comment by rabTAI** [comment]
how did you create your Honey address?

If you create a new address using `getnewaddress "legacy"`, then you can create bees using that address.
