### ISSUE TITLE
Creating Bees with a Honey Address outside of your wallet does not give error

### ISSUE THREAD

**Issue by ghost** [litecoincash-project/litecoincash#19]
**-- Describe the issue --**

Creating bees with a honey address outside your wallet does not give error, however it does not provide any block rewards to that address.

**-- What behavior did you expect? --**

An error that address is not in your wallet, since honey rewards cannot be sent to other addresses.

**-- What was the actual behavior (provide screenshots if the issue is GUI-related)? --**

Create bees is successful with a transaction ID returned.

**-- How reliably can you reproduce the issue, what are the steps to do so? --**

1. Open two wallets, generate legacy address from first wallet.  
2. Open second wallet that has enough LCC to create bees, open console and type:

createbees 10 true XXXXXXXXXXXXXXXXXXX

Where XXXXXXXXXXXXXXXXXXX is the legacy address created in step 1.

**-- What version of LitecoinCash Core are you using, where did you get it (website, self-compiled, etc)? --**

0.16.0.5 / 0.16.0.6 from repository

**Comment by litecoincash-project** [comment]
Thanks for the report! Fixed in 0.16.0.7
