### ISSUE TITLE
Hive miner ( Bee's hashes iteration loop ) Multi-Thread

### ISSUE THREAD

**Issue by ghost** [litecoincash-project/litecoincash#20]
It is possible to multi-thread the hive bee's hashes iteration loop, making the bee's hashes check time a lot faster, giving an unfair advantage to those with such a modified wallet.

I have given the code to Tanner.

**Comment by Gold969** [comment]
when someone breaks the rules, I just refuse to play) but the coin is interesting and now it is much easier to buy coins than to mine.... more than half of the blocks I did not have, bees in the minus, production... I can just keep the wallet turned on to support the network, there is no point chasing the processor.

**Comment by ghost** [comment]
At least I gave the code to the main dev as soon as I could reach him.

Up to the dev team now to continue the great work and update this.

**Comment by MerlinMagic2018** [comment]
Created a pr.

https://github.com/litecoincash-project/litecoincash/pull/21

**Comment by MerlinMagic2018** [comment]
Note that it's for an 8 threads hive miner. This could be changed or the code could be adapted to detect the number of physical cores automatically.

**Comment by litecoincash-project** [comment]
Implemented a better version ;)
