### ISSUE TITLE
Windows QT crash issue

### ISSUE THREAD

**Issue by dottat** [litecoincash-project/litecoincash#22]
Issue appears on windows QT wallet when opening wallet.  From what I can tell, if I close the wallet with TX in the mempool it will crash after re-opened until TX are processed or mempool.dat is removed.  

Observed on two different windows 10 pro machines.  One with a 3800x and one with a 3900x cpu.  Logging showed nothing other than it simply stopped logging mid statement (usually right after it starts getting peers).  When the issue is present I can restart the wallet as many times as 5 times with it crashing each time.  These machines are fairly quick and that could have something to do with the problem.  Wallet is encrypted and requires password for hivemining... which i stopped doing immediately to rule out hivemining start as a possible crash mechanism.

**Comment by dottat** [comment]
Fault bucket 1699072315607962837, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: litecoincash-qt.exe
P2: 0.16.1.2
P3: 5ddd3540
P4: ntdll.dll
P5: 10.0.18362.418
P6: 99ca0526
P7: c0000005
P8: 000000000001d25f
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER79C.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7EB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7FC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7FA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER81A.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_litecoincash-qt._9fbbc3db885eb23334b9ee8fe10342f4dcf6c57_59abc691_336ac7ca-9fb7-46f9-bcc4-2d77230b34ac

Analysis symbol: 
Rechecking for solution: 0
Report Id: a0de7481-e6a2-4df8-8d52-6e88021b8277
Report Status: 268435456
Hashed bucket: f7db0984b93eee5f47945144db8354d5
Cab Guid: 0

**Comment by litecoincash-project** [comment]
I believe this is due to a (lack of) lock in HiveDialog::updateData().

As you're the only reporter, and we can only replicate in non-production conditions, I'll test a fixing build with you privately.

**Comment by dottat** [comment]
I think it's fairly safe to say we put a fork in this...
