### ISSUE TITLE
Need ability to modify the bee count between early out checks 

### ISSUE THREAD

**Issue by dottat** [litecoincash-project/litecoincash#23]
On larger hives and especially faster hives it would appear that early out thread is checking a little too often.  Can this value be modified via qt wallet in the future?  Limiting hashing to 23 threads on a 3900x shows that the 24th thread is kept equally busy as any other thread when it's just doing early out checking.  Since total time to hash is ~230ms as is maybe early out can be configured to check at time intervals rather than bee internal (or just a higher bee count since time is already pretty low).

**Comment by litecoincash-project** [comment]
I swear I asked before Hive 1.1 release if people wanted this parameterised! It's such a micro-optimisation that I almost want to say if you want this, do a custom build... Argue hard enough and I'll schedule it for next minor rel...

[Tan]
