### ISSUE TITLE
Test failed: test/test_litecoincash - Litecoincash on a VPS server

### ISSUE THREAD

**Issue by mushroom-3000** [litecoincash-project/litecoincash#25]
This is an error report for the litecoincash core install on a VPS, i was hoping it would install correctly however the test failed...
```

FAIL: test/test_litecoincash
============================

Running 271 test cases...
test/main_tests.cpp(30): ^[[1;31;49merror: in "main_tests/block_subsidy_test": check nSubsidy == nPreviousSubsidy / 2 has failed [0 != 1192]^[[0;39;49m
unknown location(0): ^[[4;31;49mfatal error: in "rpc_tests/rpc_ban": std::runtime_error: JSON value is not an object as expected^[[0;39;49m
test/rpc_tests.cpp(266): ^[[1;36;49mlast checkpoint^[[0;39;49m

^[[1;31;49m*** 2 failures are detected in the test module "LitecoinCash Test Suite"
^[[0;39;49mFAIL test/test_litecoincash (exit status: 201)

```
How should i proceed?
Please advise...

**Comment by mushroom-3000** [comment]
I also have tried to install on a Virtual server on my local machine, also failed but this time it has just 1 failure with 1 pass, same as before:


```

FAIL: test/test_litecoincash
============================

Running 271 test cases...
unknown location(0): ^[[4;31;49mfatal error: in "rpc_tests/rpc_ban": std::runtime_error: JSON value is not an object as expected^[[0;39;49m
test/rpc_tests.cpp(266): ^[[1;36;49mlast checkpoint^[[0;39;49m

^[[1;31;49m*** 1 failure is detected in the test module "LitecoinCash Test Suite"
^[[0;39;49mFAIL test/test_litecoincash (exit status: 201)

```

**Comment by mushroom-3000** [comment]
I have no issues with windows release files when in windows

**Comment by blockester** [comment]
Try running configure while adding an additional parameter to skip tests.
'./configure --disable-tests'..

**Comment by mushroom-3000** [comment]
Thank you for your reply...

To run without tests, wouldn't this be a bad idea? 

I mean i wish to get it running, sure, but i want the tests to be performed to ensure my build is safe (secure), right? 

I could run without tests however im conscious of security implications.

What benefit comes from having the tests performed? Does it increase the security? Or just purely for providing information?

Why do my tests fail?

Do you think the issue is perhaps with the VPS itself? Or even my VPS provider?

Lots of questions that need answering. Please advise...

**Comment by blockester** [comment]
What command are you using to get this message? And which platform so that your error can be reproduced.

**Comment by litecoincash-project** [comment]
Assuming stale and closing.
