### ISSUE TITLE
Hive bee loss and multiple wallet request

### ISSUE THREAD

**Issue by mushroom-3000** [litecoincash-project/litecoincash#26]
I recently sent out 3 bee orders to the hive and i believe they were `sent` at the same time according to the information displayed in my litecoincash core, although the first 2 orders were about 10 minutes apart before my 3rd order

Maybe about a hour or 2 later my system was not shutdown properly which lead to the litecoincash folder being corrupted

I was able to recover my wallet with -salvagewallet and then rebuild the blockindex

My 1st and 2nd bee `order` was fine

However my 3rd order was missing with the transaction list before my wallet was corrupted showing it being taken from my account balance but after i reclaimed my wallet the bees are not in my hive even though the litecoincash was deducted from my balance

Now after salvaging my wallet only my first 2 bee orders are present in transaction history

How should i proceed?

Where are my precious bees?

Also when will a multi-wallet feature like bitcoin core has be added?

**Comment by blockester** [comment]
Do you have a transaction id? You could post this hash to the LCC/Ring Discord support channel.

**Comment by litecoincash-project** [comment]
Assuming stale and closing.
