### ISSUE TITLE
Litecoin Cash v0.16.3 hi after upgrading my balance is incorrect i had 7000 lcc now there is 1 562.6978306 lcc which is my first set of deposit

### ISSUE THREAD

**Issue by juvi1868** [litecoincash-project/litecoincash#34]

**Comment by dottat** [comment]
You should have updated prior to the soft fork activation.  Your balance isn't what you thought it was because you didn't update your wallet and therefore were not on the correct chain. That's why you need to pay attention to wallet updates especially ones with soft/hard fork implications.
