### ISSUE TITLE
Wallet: 0 active connections to LitecoinCash network?!

### ISSUE THREAD

**Issue by virus0190** [litecoincash-project/litecoincash#6]
Windows 64-bit.
Seems there is problem. Somebody else the same??

**Comment by laris2** [comment]
You can try adding nodes to litecoincash.conf located in data dir.
It seems that seednodes are a bit overloaded at the moment.
addnode=159.89.6.189:62458
addnode=73.130.131.19
addnode=207.201.218.201
addnode=70.160.76.254
addnode=24.99.21.129
addnode=103.69.195.170
addnode=69.143.82.147:62458
addnode=192.111.148.136:62458
addnode=178.62.215.167:62458
addnode=80.108.41.4:62458
addnode=46.43.9.237:62458
addnode=144.202.8.82:62458
addnode=35.231.82.152:62458
addnode=54.64.147.208:62458
addnode=35.189.144.78:62458
addnode=24.129.114.44:62458
addnode=46.101.118.113:62458
addnode=144.202.8.82:62458
addnode=45.63.89.33:62458
addnode=66.70.180.59:62458
addnode=108.249.146.109:62458
addnode=35.231.82.152:62458
addnode=178.62.215.167:62458
addnode=46.43.9.237:62458

**Comment by virus0190** [comment]
Great! Worked for me. Thanks
