### ISSUE TITLE
Problem with new wallet Orphaned Blocks

### ISSUE THREAD

**Issue by dexametazon** [litecoincash-project/litecoincash#6]
hi 
I am one of the solo miners of the LCC 
I'm a mine with my own NOMP 
I used a uNOMP before the new update of the wallet, And I got a few Blocks
But in the new version of wallet, we have to use the NOMP 
Since I'm using a new version of the wallet
So far, I have found 2 blocks, both orphans
I think this is a problem with the new version of wallet and i cant download Previous version
After finding my first orphaned Block, I reset the server (NOMP)
But just a few hours ago, I found a second Block, the orphan
I use my old laptop as a server
If I find an orphan again, I will announce here
can i have link for download previous version ( LitecoinCashCore:0.15.0.1)
![capture1](https://user-images.githubusercontent.com/23564495/43233453-3818c3b8-908b-11e8-9406-77a52fe2136c.JPG)
![capture2](https://user-images.githubusercontent.com/23564495/43233454-38457228-908b-11e8-89b5-6d6794c8283e.png)
![capture3](https://user-images.githubusercontent.com/23564495/43233455-3872fa5e-908b-11e8-89d2-71dec829ba29.JPG)
![photo_2018-07-26_04-16-20](https://user-images.githubusercontent.com/23564495/43233456-38a32986-908b-11e8-99aa-4d2a87b11fca.jpg)

**Comment by dexametazon** [comment]
I found another orphan block
![capture1](https://user-images.githubusercontent.com/23564495/43254487-bbf434dc-90dc-11e8-84fc-b388c4b8995c.JPG)
![capture2](https://user-images.githubusercontent.com/23564495/43254502-c36a3c98-90dc-11e8-943c-ed25fd60a0f6.png)

**Comment by red0bear** [comment]
I found 4 orphaned !!!! :-))))

**Comment by laakie** [comment]
Can confirm the same behaviour.
would be nice if we can downgrade to 015..
Until we can find out what is causing this.

**Comment by red0bear** [comment]
@laakie this is caused beccause nomp accept only legacy hash key to submmit payout to miners.

**Comment by laakie** [comment]
So I need to use a legacy key for the coinbase ?
Lol. That's odd :D

**Comment by red0bear** [comment]
@laakie for wallet you need use legacy address to make payout to miners and payment fees. To miners is not necessary to use legacy address.

**Comment by laakie** [comment]
Confirmed to be a working solution. 
Thanks red0bear! Appreciate the quick response. :)

**Comment by red0bear** [comment]
Give me 30 litecoincash for response LOL.

**Comment by laakie** [comment]
Why not ! LOL
Address please

**Comment by red0bear** [comment]
lets try --> MSwNp88Rwo7EdWVpYLG8MVB5bbBoxfe1Kp

**Comment by red0bear** [comment]
RECEIVED .. THANK YOU.

**Comment by litecoincash-project** [comment]
Great - thanks all :)
