### ISSUE TITLE
RPC Net Port

### ISSUE THREAD

**Issue by vr4dude316** [litecoincash-project/litecoincash#7]
Which port # should I use for my conf file to connect?

**Comment by vr4dude316** [comment]
rpcuser=rpcuserxxxx
rpcpassword=paswordxxxx
server=1
daemon=1
listen=1
rpcport=9332

**Comment by vr4dude316** [comment]
litecoincashd -daemon will not start complaining of incorrect RPC port

**Comment by litecoincash-project** [comment]
try rpcbind instead of rpcport:
rpcbind=9332

**Comment by litecoincash-project** [comment]
Try also specifying allowed RPC ip, and ip to bind to:

rpcallowip=127.0.0.1
rpcbind=127.0.0.1

You shouldn't need listen and daemon; server=1 should be enough.

My complete config looks similar to:

rpcuser=rpctest
rpcpassword=rpctest
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
server=1

(and I connect via the default RPC port 62457)

**Comment by vr4dude316** [comment]
Thank you.  Will give a shot.  Using UNOMP pool on ubuntu 14.04
For the coin config, do i need peer magic included?

**Comment by litecoincash-project** [comment]
If you'd like p2p block notifications, then yes: try "c7e4baf8" for your peerMagic config

**Comment by vr4dude316** [comment]
Thank you... still no joy
unomp@ubuntu:~/unomp$ litecoincashd -daemon
LitecoinCash server starting
unomp@ubuntu:~/unomp$ litecoincash-cli getblockchaininfo
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
 config:
rpcuser=poolrpcuser
rpcpassword=387dgDPc9Dj7Z6XESN7dHeESbqBa6u9xQc
server=1
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=62457

Weird thing is, it was running and downloaded the entire blockchain.  i bounced my box and now wont start back

**Comment by litecoincash-project** [comment]
Hmmm, can you paste some of debug.log after startup happens?

Edit: Also, if you litecoincash.conf isn't at ~/.litecoincash/litecoincash.conf, pass both litecashd and litecoincash-cli the argument --conf=/path/to/litecoincash.conf

**Comment by red0bear** [comment]
Do you have magic number correct and more peers ?

**Comment by vr4dude316** [comment]
I just wiped everything out and compiling fresh.  Thanks for the help.  Will post back once running again.  my conf file is in the /.litecoincash dir.  As for magic number, not sure what you mean.  Im just a moderate noob at linux

**Comment by litecoincash-project** [comment]
Assuming you sorted this; feel free to open a new Issue if not.
