### ISSUE TITLE
TX send not showing

### ISSUE THREAD

**Issue by vr4dude316** [litecoincash-project/litecoincash#8]
Hello.  Just a test from my wallet.  1st tx sent fine.  10lcc
2nd tx says it sent, but doesn't exist.  of course this was the balance of my wallet.  where are the coins?

 {
    "account": "",
    "address": "Ce6ZhX8e2Zyn4wPCTW5MswDW1wfQjpAn7t",
    "category": "send",
    "amount": -2240.0000000,
    "vout": 1,
    "fee": -0.0001370,
    "confirmations": 0,
    "trusted": true,
    "txid": "a4100e6d86072ac09360f86c76573bd420961e3c013d8ea41c71f228f9348227",
    "walletconflicts": [
    ],
    "time": 1536366454,
    "timereceived": 1536366454,
    "bip125-replaceable": "no",
    "abandoned": false
  }
]

**Comment by litecoincash-project** [comment]
Hi, sorry for the delay; tx exists so closing.
